name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}
    - name: Deploy Test1 
      run: cd test1 && aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}/test1
    - name: Current dir
      run: pwd
    - name: Deploy Except Test1
      run:  aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --exclude "test1"








    #- uses: jakejarvis/s3-sync-action@master
    #  with:
    #    args: --follow-symlinks --delete --exclude '.git/*' 'test1/*' 'test2/*' #--acl public-read for public buckets
    #  env:
    #    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    AWS_REGION: ${{ secrets.AWS_REGION}}  
    
      
